name: Build Pkgs

on:
  workflow_dispatch:
  
jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Set up swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
          
      - uses: Ste74/build-pkgs@main
        with:
          repo-src: "https://gitlab.manjaro.org/packages/community/inxi"
          gitlab-user: ${{ secrets.gitlab_user }}
          gitlab-pw: ${{ secrets.gitlab_server_user }}
          user-mail: ${{ secrets.manjaro_mail }}
          manjaro-user: ${{ secrets.manjaro_user }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          branch: "unstable"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-key-sign: ${{ secrets.GPG_SIGN }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
